version: '3.4'

services:
  rater:
    command: bash -c "watchmedo auto-restart --pattern "*.py" --recursive --signal SIGTERM python main.py"
    restart: always
    volumes:
      - .:/rater
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      PYTHONUNBUFFERED: 1
